### ISSUE TITLE
r2beta chokes on interactions in random effects

### ISSUE THREAD

**Issue by ashenkin** [bcjaeger/r2glmm#2]
Hi there,

I have a model such as : `lmer(dep ~ ind + (1|a:b), data = df)`.  r2beta throws a "`Error in `[.data.frame`(data, , clust.id) : undefined columns selected`" error when passed this model, even when supplying the data argument.  However, if i make a column `df$c = paste0(df$a, df$b)` and run` lmer(dep ~ ind + (1|c), data = df)`, r2glmm works just fine.

**Comment by bcjaeger** [comment]
Thanks! I fixed the issue and updated the r2beta.lmerMod function.

**Comment by theclairecamp** [comment]
Hi! I'm still getting this error, I have a function written as `model <- lmer(outcome ~ predictor + (1 | site:subject), data = df)`.
I run `r2beta(model, method = 'kr')` and still get the error `Error in '[.data.frame'(data, , clust.id) : undefined columns selected`.
The `r2beta` function runs fine if I remove the random effect of `subject` from the model. 
I've checked, and I think I have the most current version: [0.1.2](https://cran.r-project.org/web/packages/r2glmm/r2glmm.pdf)

**Comment by bcjaeger** [comment]
Hello, @theclairecamp! This is most likely because I forgot to bump the version of `r2glmm` to 0.1.2.9001 when I implemented this fix (sorry, I barely knew what I was doing with R packages back then 😅) 

I checked to make sure this example would run with the current dev version of r2glmm (see reprex below), and I just bumped the version to 0.1.2.9001 on GitHub so that the development version won't appear to be the CRAN version. Can you try installing the most recent version from GitHub using `remotes::install_github("bcjaeger/r2glmm")` and let me know if the example runs as intended?

``` r
library(tibble)
library(lme4)
#> Loading required package: Matrix
library(r2glmm)

df <- tibble(
  site = rep(letters[1:5], each = 20),
  subject = rep(LETTERS[1:20], eac = 5),
  predictor = rnorm(100),
  outcome = predictor + 
    rep(rnorm(n=5), each = 20) + 
    rep(rnorm(n=20), each = 5) + 
    rnorm(100)
)

m <- lmer(outcome ~ predictor + (1 | site:subject), data = df)

# note the higher partial R2 is due to KR DDF, not an r2glmm mechanic.
# use method = 'sgv' or 'nsj' to get more stable estimates.
r2beta(m, method = 'kr')
#>      Effect   Rsq upper.CL lower.CL
#> 2 predictor 0.565    0.678    0.440
#> 1     Model 0.564    0.678    0.439
```

<sup>Created on 2024-05-20 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by theclairecamp** [comment]
Just downloaded the new GitHub version and ran your example and it ran great! Thanks so much!

**Comment by bcjaeger** [comment]
Awesome! Happy to help. Thanks for using `r2glmm`!
